[metadata]
name = cen-standard-renderer
version = 0.0.1
author = Q Misell
author_email = qmisell@mpi-inf.mpg.de
description = Compile Markdown files into CEN standard Word files.
license_file = LICENSE.md
url = https://github.com/TheEnbyperor/cen-standard-renderer
project_urls =
    Bug Tracker = https://github.com/TheEnbyperor/cen-standard-renderer/issues

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.11
install_requires =
    marko
    pyyaml
    python-docx

[options.packages.find]
where = src

[options.package_data]
asn1docs =
    templates/**